name: alisveris_sepeti
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Proje Paketleri
  provider: ^6.1.2
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  flutter_native_splash: ^2.4.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter'a özel ayarlar
flutter:
  uses-material-design: true

  # Flutter'a resimlerimizin bulunduğu klasörü burada tanıtıyoruz.
  assets:
    - assets/images/

# Açılış ekranı paketinin ayarları burada yer alır.
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png

  # ANDROID İÇİN AYARLAR
  # 'gravity' parametresi resmin nasıl yerleşeceğini belirler.
  # 'fill' ekranı tamamen kaplamasını sağlar. 'center' ise ortalar.
  android_gravity: fill

  # WEB İÇİN AYARLAR
  # 'web_image_mode' webdeki görünümü ayarlar.
  # 'contain' oranları bozmadan ekrana sığacak en büyük boyuta getirir.
  web_image_mode: contain
