// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxeU3zWVVFMNU-Yuy-ieY5jcKx6u_be1E',
    appId: '1:453777378204:web:fef1edf3a08d63af7d1659',
    messagingSenderId: '453777378204',
    projectId: 'alisverissepeti-10270',
    authDomain: 'alisverissepeti-10270.firebaseapp.com',
    storageBucket: 'alisverissepeti-10270.firebasestorage.app',
    measurementId: 'G-3SY95B5WNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwMs76yk8GnRJ5V_5AWvMjDm8lJU6ZFck',
    appId: '1:453777378204:android:3ba5c5faf390c0407d1659',
    messagingSenderId: '453777378204',
    projectId: 'alisverissepeti-10270',
    storageBucket: 'alisverissepeti-10270.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEEhRBkg1zyqMihAqWEsWZV0QvRnGds6k',
    appId: '1:453777378204:ios:4784641eebf785897d1659',
    messagingSenderId: '453777378204',
    projectId: 'alisverissepeti-10270',
    storageBucket: 'alisverissepeti-10270.firebasestorage.app',
    iosBundleId: 'com.example.alisverisSepeti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEEhRBkg1zyqMihAqWEsWZV0QvRnGds6k',
    appId: '1:453777378204:ios:4784641eebf785897d1659',
    messagingSenderId: '453777378204',
    projectId: 'alisverissepeti-10270',
    storageBucket: 'alisverissepeti-10270.firebasestorage.app',
    iosBundleId: 'com.example.alisverisSepeti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxeU3zWVVFMNU-Yuy-ieY5jcKx6u_be1E',
    appId: '1:453777378204:web:76c82eb1eae7004e7d1659',
    messagingSenderId: '453777378204',
    projectId: 'alisverissepeti-10270',
    authDomain: 'alisverissepeti-10270.firebaseapp.com',
    storageBucket: 'alisverissepeti-10270.firebasestorage.app',
    measurementId: 'G-9RKENFC39D',
  );

}